version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:80
    volumes:
      - ./drupal/modules:/bitnami/drupal/modules
      - ./drupal/themes:/bitnami/drupal/themes
      - ./drupal/sites:/bitnami/drupal/sites
    restart: always
    environment:
      - MARIADB_HOST=database
      - MARIADB_DATABASE=drupal
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=drupal
    depends_on:
      - database
      - webserver

  webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    depends_on:
      - drupal

  certbot:
    image: certbot
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - webserver
